### ISSUE TITLE
Error building container

### ISSUE THREAD

**Issue by cdarken** [antage/docker-apache2-php5#1]
I get this error while the container is building:

```
2017-11-12T14:16:49Z 455f04144eca /usr/local/bin/confd[10]: ERROR template: msmtprc.tmpl:8:7: executing "msmtprc.tmpl" at <getv "/php/smtp">: error calling getv: key does not exist
```

Did I miss some configuration option?

**Comment by antage** [comment]
@cdarken To run the container you must define `PHP_SMTP` and `PHP_SMTP_FROM` environment variables. Like this:
```
docker run --rm -e PHP_SMTP=172.17.0.1 -e PHP_SMTP_FROM=noreply@localhost apache2-php5
```

**Comment by cdarken** [comment]
@antage am I guessing right that those constants are automatically converted to these keys?
```
keys = [
    "/php/smtp",
    "/php/smtp/from"
]
```
I've never used confd until now and I don't really understand how it works.

**Comment by antage** [comment]
@cdarken You are guessing right.
`confd` transforms environment variable name to key name [replacing](https://github.com/kelseyhightower/confd/blob/f711530db830232d00e862ec69125173b4e726bf/backends/env/client.go#L49)  '_' to '/'.

**Comment by cdarken** [comment]
@antage in that case maybe a mention in the Readme or some placeholder default values for them would be helpful, what do you think?

**Comment by antage** [comment]
@cdarken I added 'Required variables' section (f94d1974a185494ff19a9fd7fbe8105505f093cd).

**Comment by cdarken** [comment]
Thank you for your assistance.
