### ISSUE TITLE
Php mysql extension not loaded 

### ISSUE THREAD

**Issue by saviobosco** [antage/docker-apache2-php5#2]
The php_mysql and mysql_pdo extensions are not loaded in web and cli. I have tried mount php ini path in a separate volume but to no avail. And also please what is the use of the `PHP_MOD` env variable .

**Comment by antage** [comment]
Almost all php extension is disabled by default. You can enable it with `PHP_MODS` environment variable:
`PHP_MODS='mysql,pdo_mysql'`.
